### ISSUE TITLE
Out of Sync warning

### ISSUE THREAD

**Issue by gedanziger** [norestlabs/mousexplore-vcoins#320]
Add a warning if the block explorer is out of sync, similar to the monitoring. Add a configurable `OUT_OF_SYNC_NOTIFY_THRESHOLD` param. If the current time is greater than the most recent block time by this amount or more, we should report as out degraded/out of sync to monitoring services.

For most of blockchains, set this to 30 mins. We should be able to tune to smaller amounts.

**Comment by ohtayoshida** [comment]
@gedanziger @oleg-baturov 
How to notify in case of syncing out?

**Comment by oleg-baturov** [comment]
Need to respond the same format as monitor apis. @ohtayoshida
