### ISSUE TITLE
Eterherum transactions cron is not syncing

### ISSUE THREAD

**Issue by oleg-baturov** [norestlabs/mousexplore-vcoins#339]
Ethereum node is syncing correctly, and out-of-syncing api is working.
But cron service to fetch transactions is not syncing at all.

![image](https://user-images.githubusercontent.com/32242962/51510733-00b84400-1e4a-11e9-82d4-0b6110b8668a.png)

**Comment by ohtayoshida** [comment]
@oleg-baturov 
It fails in case of error transactions.
![image](https://user-images.githubusercontent.com/39059740/51514870-4cc0b400-1e5d-11e9-8f99-9399890c1563.png)

It was just fixed by #338

**Comment by oleg-baturov** [comment]
Verified by 61c7f3435314b93163cb30644c23e3e5f5ffd457
