### ISSUE TITLE
NEO node is not syncing

### ISSUE THREAD

**Issue by oleg-baturov** [norestlabs/mousexplore-vcoins#340]
Neo node is not syncing from block 3260794.
![image](https://user-images.githubusercontent.com/32242962/51583801-f8c9d400-1f1d-11e9-9f70-b2b19fd32d1c.png)

**Comment by ohtayoshida** [comment]
Instead of neo.service, I started neo rpc daemon by using screen.
It will work.
@oleg-baturov

**Comment by oleg-baturov** [comment]
ok, neo node is freezing by cache when running service.
Let's watch how screen daemon goes.

**Comment by oleg-baturov** [comment]
screen daemon working good.
