### ISSUE TITLE
loom chain vcoins seed and readme

### ISSUE THREAD

**Issue by oleg-baturov** [norestlabs/mousexplore-vcoins#341]
Create loom chain vcoins seed.
Add readme.

Support should be added for ERC721x assets

**Comment by gedanziger** [comment]
For this issue, we need to support ERC721x asset (loom network version of 721 non fungible tokens)

**Comment by gedanziger** [comment]
For this issue, we need to support ERC721x asset (loom network version of 721 non fungible tokens)

**Comment by oleg-baturov** [comment]
Verified by 8c71b7be846db981423ee30fc5d74a88634b28da
